### ISSUE TITLE
Celcat Web API documentation

### ISSUE THREAD

**Issue by sterichards** [neilherbertuk/celcatwebapi#1]
Hi,

Are you able to provide the Celcat Web API documentation that was used to implement this wrapper?

I can't find any documentation on Celcats website

**Comment by neilherbertuk** [comment]
Hi @sterichards,

There are a few places you can get the documentation from, 

The Celcat Web API has a built-in instance of swagger which you can find at https://celcatserver:5000/swagger/ui/index.html - you are meant to be able to test your API endpoints with swagger but Celcat haven't gotten this working.

They also have documentation on the wiki at https://www.celcat.wiki/en/guides/developers_guides/webapi/webapi

This wrapper is a work in progress and hasn't reached anywhere near a v1!

Neil

**Comment by sterichards** [comment]
Very kind, thank you!

**Comment by neilherbertuk** [comment]
Not a problem, I've only implemented what I need from the API so far. This only involves gets so far. Happy to receive PRs if you want to add anything to this.
